
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alejandrodietta
 */
public class MiFrame extends javax.swing.JFrame {

    conexiones gesCon = new conexiones();
    DefaultTableModel modeloTabla;
    ImageIcon iconLogo = new ImageIcon("imagenes/jimmy.jpg");
    Statement sta;
    String preso;
    int pat;
    //cremaos unas Variables para comprobar los telefonos que tiene el preso para a la hora de modificar la nested table en funcion
        //de si ya lo tiene se tendra que modificar o añadir uno nuevo 
        boolean nuevoTelMovil = true;  boolean nuevoTelAbogado = true;  boolean nuevoTelFamiliar = true;

    /**
     * Creates new form MiFrame
     */
    public MiFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jComboBox3.addItemListener(itemListener);
//          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jimmy.jpg")));    
        gesCon.GestorConexion();

        gesCon.consulta_Statement("select * from preso", jTable1, 2);
        jTable1.setRowHeight(25);

        ////////// JDIALOGGGG ///////////
        jDialogInsertarDelito.setLocationRelativeTo(null);
        ////////// JDIALOGGGG ///////////

        //listener para la tabla 1 de presos para que cuando se pulse click derecho en una las filas, un preso, 
        //se carge un nuevo panel con los datos del preso 
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {

                if (SwingUtilities.isRightMouseButton(e)) {
                    Point p = e.getPoint();
//                JTable target = (JTable)e.getSource();
                    int row = jTable1.rowAtPoint(p);
                    String id = (String) jTable1.getModel().getValueAt(row, 0);
                    
                    //Guardo la clave primaria del preso para despues saber de quien cargar los datos en el perfil
                    preso = id;
                    cambiarPanel(jPanelPerfilPreso);
                    cargaPerfilPreso(preso);
                    //resteo las circunstancias epor si tiene las de algun preos anterior
                     jTextArea1.setText("");
                }
            }
        });

        //listener para la tabla de los delitos dentro del perfil de preso para que cuando se seleccione uno 
        //aparezna en el textbox de circunstancias estas, para una mejor vision de las mismas 
        jTable2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {

                JTable target = (JTable) e.getSource();
                int row = target.getSelectedRow();
                String circunstancias = (String) jTable2.getModel().getValueAt(row, 2);
                jTextArea1.setText(circunstancias);

            }
        });

//        Image scaledImage = originalImage.getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBusquedaAvanzada = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jDialogInsertarDelito = new javax.swing.JDialog();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButtonCancelarAddDelito = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButtonAceptarAddDelito = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaDescNuevoDelito = new javax.swing.JTextArea();
        jLabelErrorInsetarDelito = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDialogModificarTelefono = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelInicio = new javax.swing.JPanel();
        jButtonEliminarPreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxConsultaPresos = new javax.swing.JComboBox<>();
        jTextFieldConsultaPreso = new javax.swing.JTextField();
        jButtonBuscarPreso = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButtonBusquedaAvanzada = new javax.swing.JButton();
        jButtonNuevoPreso = new javax.swing.JButton();
        jPanelPerfilPreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextFieldDniPresoPerfil = new javax.swing.JTextField();
        jTextFieldApellidoPresoPerfil = new javax.swing.JTextField();
        jTextFieldNacionalidadPresoPerfil = new javax.swing.JTextField();
        jTextFieldAlturaPresoPerfil = new javax.swing.JTextField();
        jTextFieldBandaPreso = new javax.swing.JTextField();
        jTextFieldPielPresoPerfil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButtonAtrasPerfilPreso = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNombrePresoPerfil = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCodigoPresoPerfil = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabelErrorPerfil = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtonModificarTelPreso = new javax.swing.JButton();
        jPanelAddDelito = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanelAddPreso = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButtonAtrasInsertasPreso = new javax.swing.JButton();
        jButtonAddPreso = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();

        jDialogBusquedaAvanzada.setMinimumSize(new java.awt.Dimension(365, 373));

        jButton10.setText("Buscar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cancelar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Busqueda Avanzada");

        jLabel25.setText("Nombre");

        jLabel26.setText("Apellido");

        jLabel27.setText("Nacionalidad");

        jLabel28.setText("Color de piel");

        jLabel29.setText("Banda");

        javax.swing.GroupLayout jDialogBusquedaAvanzadaLayout = new javax.swing.GroupLayout(jDialogBusquedaAvanzada.getContentPane());
        jDialogBusquedaAvanzada.getContentPane().setLayout(jDialogBusquedaAvanzadaLayout);
        jDialogBusquedaAvanzadaLayout.setHorizontalGroup(
            jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBusquedaAvanzadaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addGap(50, 50, 50)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBusquedaAvanzadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBusquedaAvanzadaLayout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(28, 28, 28)
                        .addComponent(jButton10)))
                .addGap(90, 90, 90))
        );
        jDialogBusquedaAvanzadaLayout.setVerticalGroup(
            jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBusquedaAvanzadaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jDialogBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(32, 32, 32))
        );

        jDialogInsertarDelito.setMinimumSize(new java.awt.Dimension(772, 413));

        jLabel19.setText("Codigo delito:");

        jTextField14.setEnabled(false);

        jButtonCancelarAddDelito.setText("Cancelar");
        jButtonCancelarAddDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAddDelitoActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAceptarAddDelito.setText("Aceptar");
        jButtonAceptarAddDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarAddDelitoActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jLabel20.setText("Circunstancias");

        jLabel21.setText("Lugar de los hechos:");

        jLabel22.setText("Descripcion:");

        jLabel23.setText("Condena:");

        jTextAreaDescNuevoDelito.setColumns(20);
        jTextAreaDescNuevoDelito.setRows(5);
        jTextAreaDescNuevoDelito.setEnabled(false);
        jScrollPane7.setViewportView(jTextAreaDescNuevoDelito);

        jLabelErrorInsetarDelito.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setText("Codigo:");

        jTextField1.setEnabled(false);

        javax.swing.GroupLayout jDialogInsertarDelitoLayout = new javax.swing.GroupLayout(jDialogInsertarDelito.getContentPane());
        jDialogInsertarDelito.getContentPane().setLayout(jDialogInsertarDelitoLayout);
        jDialogInsertarDelitoLayout.setHorizontalGroup(
            jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogInsertarDelitoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelarAddDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonAceptarAddDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(247, 247, 247)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelErrorInsetarDelito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField13)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                                .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel7))
                                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDialogInsertarDelitoLayout.setVerticalGroup(
            jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogInsertarDelitoLayout.createSequentialGroup()
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jLabelErrorInsetarDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jDialogInsertarDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarAddDelito)
                    .addComponent(jButtonAceptarAddDelito))
                .addGap(30, 30, 30))
        );

        jDialogModificarTelefono.setMaximumSize(new java.awt.Dimension(358, 291));
        jDialogModificarTelefono.setMinimumSize(new java.awt.Dimension(358, 291));
        jDialogModificarTelefono.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("Movil:");
        jDialogModificarTelefono.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 48, -1, -1));

        jLabel45.setText("Abogado:");
        jDialogModificarTelefono.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 94, -1, -1));

        jLabel46.setText("Familiar Contacto:");
        jDialogModificarTelefono.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 142, -1, -1));
        jDialogModificarTelefono.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 45, 163, -1));
        jDialogModificarTelefono.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 91, 163, -1));
        jDialogModificarTelefono.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 139, 163, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialogModificarTelefono.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton6.setText("Modificar Telefonos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialogModificarTelefono.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContenedor.setMaximumSize(new java.awt.Dimension(980, 626));
        jPanelContenedor.setLayout(new java.awt.CardLayout());

        jPanelInicio.setMaximumSize(new java.awt.Dimension(980, 626));
        jPanelInicio.setMinimumSize(new java.awt.Dimension(980, 626));
        jPanelInicio.setPreferredSize(new java.awt.Dimension(980, 626));

        jButtonEliminarPreso.setText("Eliminar Seleccionados");
        jButtonEliminarPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPresoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jComboBoxConsultaPresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los presos", "Preso con DNI: ", "Preso con Código:", "Presos con Nombre:", "Presos con Apellido:", "Presos con Fecha de Nacimiento en:", "Presos con Nacionalidad:", "Presos con Color de piel:", "Presos con Altura:", "Presos de la Banda:", "Presos condenados antes de:", "Presos condenados después de:" }));
        jComboBoxConsultaPresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsultaPresosActionPerformed(evt);
            }
        });

        jTextFieldConsultaPreso.setEnabled(false);

        jButtonBuscarPreso.setText("Buscar");
        jButtonBuscarPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPresoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        jLabel24.setText("PRESOS");

        jButtonBusquedaAvanzada.setText("Busqueda Avanzada");
        jButtonBusquedaAvanzada.setToolTipText("");
        jButtonBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaAvanzadaActionPerformed(evt);
            }
        });

        jButtonNuevoPreso.setText("Añadir Preso");
        jButtonNuevoPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoPresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                        .addComponent(jComboBoxConsultaPresos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConsultaPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarPreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNuevoPreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarPreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButtonNuevoPreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarPreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxConsultaPresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConsultaPreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPreso)
                    .addComponent(jButtonBusquedaAvanzada))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelContenedor.add(jPanelInicio, "card2");

        jPanelPerfilPreso.setMaximumSize(new java.awt.Dimension(980, 626));
        jPanelPerfilPreso.setMinimumSize(new java.awt.Dimension(980, 626));
        jPanelPerfilPreso.setPreferredSize(new java.awt.Dimension(980, 626));
        jPanelPerfilPreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anonimo.jpg"))); // NOI18N
        jPanelPerfilPreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 150, 170));

        jScrollPane2.setViewportView(jTable2);

        jPanelPerfilPreso.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 890, 210));

        jTextFieldDniPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldDniPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jTextFieldApellidoPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldApellidoPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jTextFieldNacionalidadPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldNacionalidadPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jTextFieldAlturaPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldAlturaPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jTextFieldBandaPreso.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldBandaPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        jTextFieldPielPresoPerfil.setMinimumSize(new java.awt.Dimension(170, 26));
        jTextFieldPielPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldPielPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel2.setText("Apellidos:");
        jPanelPerfilPreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel4.setText("Altura:");
        jPanelPerfilPreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel5.setText("Color de piel:");
        jPanelPerfilPreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel6.setText("Nacionalidad:");
        jPanelPerfilPreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 20));

        jLabel8.setText("Banda:");
        jPanelPerfilPreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel9.setText("DNI:");
        jPanelPerfilPreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanelPerfilPreso.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 274, 530, 90));

        jLabel11.setText("Circunstancias delito seleccionado:");
        jPanelPerfilPreso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jButtonAtrasPerfilPreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/go_previous_black.png"))); // NOI18N
        jButtonAtrasPerfilPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasPerfilPresoActionPerformed(evt);
            }
        });
        jPanelPerfilPreso.add(jButtonAtrasPerfilPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jButton4.setText("Añadir delito");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelPerfilPreso.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel12.setText("Fecha Nacimiento:");
        jPanelPerfilPreso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jTextFieldNombrePresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldNombrePresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel13.setText("Nombre:");
        jPanelPerfilPreso.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jTextFieldCodigoPresoPerfil.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelPerfilPreso.add(jTextFieldCodigoPresoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel44.setText("Codigo Preso:");
        jPanelPerfilPreso.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabelErrorPerfil.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorPerfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelPerfilPreso.add(jLabelErrorPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 520, 20));

        jLabel38.setText("Telefono");
        jPanelPerfilPreso.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelPerfilPreso.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, -1));

        jButton1.setText("Modificar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelPerfilPreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 150, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jPanelPerfilPreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 14, 460, 20));
        jPanelPerfilPreso.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 170, 26));

        jButtonModificarTelPreso.setText("jButton8");
        jButtonModificarTelPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTelPresoActionPerformed(evt);
            }
        });
        jPanelPerfilPreso.add(jButtonModificarTelPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 30, -1));

        jPanelContenedor.add(jPanelPerfilPreso, "card3");

        jPanelAddDelito.setMaximumSize(new java.awt.Dimension(777, 468));
        jPanelAddDelito.setMinimumSize(new java.awt.Dimension(777, 468));
        jPanelAddDelito.setPreferredSize(new java.awt.Dimension(777, 468));

        jLabel14.setText("Codigo delito:");

        jTextField12.setEnabled(false);

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton7.setText("Aceptar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jLabel15.setText("Circunstancias");

        jLabel16.setText("Lugar de los hechos:");

        jLabel17.setText("Descripcion:");

        jLabel18.setText("Condena:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanelAddDelitoLayout = new javax.swing.GroupLayout(jPanelAddDelito);
        jPanelAddDelito.setLayout(jPanelAddDelitoLayout);
        jPanelAddDelitoLayout.setHorizontalGroup(
            jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(247, 247, 247)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanelAddDelitoLayout.setVerticalGroup(
            jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAddDelitoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanelAddDelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jPanelContenedor.add(jPanelAddDelito, "card4");

        jPanelAddPreso.setMaximumSize(new java.awt.Dimension(980, 626));
        jPanelAddPreso.setMinimumSize(new java.awt.Dimension(980, 626));
        jPanelAddPreso.setPreferredSize(new java.awt.Dimension(980, 626));
        jPanelAddPreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anonimo.jpg"))); // NOI18N
        jPanelAddPreso.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 150, 170));

        jTable3.setEnabled(false);
        jScrollPane8.setViewportView(jTable3);

        jPanelAddPreso.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 890, 210));

        jTextField8.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 30));

        jTextField18.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 30));

        jTextField21.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 30));

        jTextField22.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 30));

        jTextField23.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jTextField24.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 170, -1));

        jTextField25.setMinimumSize(new java.awt.Dimension(170, 26));
        jTextField25.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel31.setText("Nombre:");
        jPanelAddPreso.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        jLabel32.setText("Fecha Nacimiento:");
        jPanelAddPreso.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));

        jLabel33.setText("Lugar Nacimiento:");
        jPanelAddPreso.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel34.setText("Apellido:");
        jPanelAddPreso.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 20));

        jLabel35.setText("Color de piel: ");
        jPanelAddPreso.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel36.setText("Nacionalidad:");
        jPanelAddPreso.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel37.setText("DNI: ");
        jPanelAddPreso.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 20));

        jButtonAtrasInsertasPreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/go_previous_black.png"))); // NOI18N
        jButtonAtrasInsertasPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasInsertasPresoActionPerformed(evt);
            }
        });
        jPanelAddPreso.add(jButtonAtrasInsertasPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jButtonAddPreso.setText("Añadir Preso");
        jButtonAddPreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPresoActionPerformed(evt);
            }
        });
        jPanelAddPreso.add(jButtonAddPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 30));

        jTextField26.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel40.setText("Altura:");
        jPanelAddPreso.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jTextField27.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel41.setText("Banda:");
        jPanelAddPreso.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jTextField28.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel42.setText("Codigo Preso");
        jPanelAddPreso.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jTextField29.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        jLabel43.setText("Foto URL:");
        jPanelAddPreso.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        jTextField30.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jTextField31.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 170, -1));

        jLabel47.setText("Telefono Abogado:");
        jPanelAddPreso.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabel48.setText("Telefono Movil:");
        jPanelAddPreso.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jTextField32.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanelAddPreso.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        jLabel49.setText("Telefono Familiar:");
        jPanelAddPreso.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jPanelContenedor.add(jPanelAddPreso, "card3");

        getContentPane().add(jPanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Carga en el combobox del jDialog de insertar delito los codigos de delitos que estan registrados en la bse de datos
    private void actualizarComboDelitos() {
        try {
            pat = 0;
            Statement sta = gesCon.conn1.createStatement();

            ResultSet rs = sta.executeQuery("select codigo_delito from delito");

            //Elimino el listener y se lo vuelvo a añadir despues de borrar el combobox, de lo contrario habia conflictos
            jComboBox3.removeItemListener(itemListener);
            jComboBox3.removeAllItems();
            jComboBox3.addItemListener(itemListener);
            jComboBox3.addItem("");
            System.out.println(pat + "ERROR");
            while (rs.next()) {
                pat = rs.getInt("codigo_delito");
                jComboBox3.addItem(String.valueOf(pat));

            }
            sta.close();
            rs.close();
            jComboBox3.addItem("Nuevo Delito");

        } catch (Exception e) {
            System.out.println("ERROORORORORRORORO");
        }
    }

    //al dar al boton de eliminar preso aparece un joptionpane para confirmar la operacion
    private void jButtonEliminarPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPresoActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea eliminar los presos seleccionados?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {     
            gesCon.borrarDatos(jTable1, "preso");    
            System.out.println("MiFrame.jButtonEliminarPresoActionPerformed()");
        }

    }//GEN-LAST:event_jButtonEliminarPresoActionPerformed

    private void jButtonAtrasPerfilPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasPerfilPresoActionPerformed
       cambiarPanel(jPanelInicio);
    }//GEN-LAST:event_jButtonAtrasPerfilPresoActionPerformed

    //En funcion de si la consulta decsira un jtext para completarse se activa o no 
    private void jComboBoxConsultaPresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsultaPresosActionPerformed
        String consulta = (String) jComboBoxConsultaPresos.getSelectedItem();
        if (consulta.equals("Todos los presos")) {
            if (jTextFieldConsultaPreso.isEnabled()) {
                jTextFieldConsultaPreso.setText("");
                jTextFieldConsultaPreso.setEnabled(false);
            }
        } else {
            if (!jTextFieldConsultaPreso.isEnabled()) {
                jTextFieldConsultaPreso.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jComboBoxConsultaPresosActionPerformed

    //Item listener para el combobox que carga los delitos existentes
    //por problemas lo he tenido que crear manual 
    //para regular que los textboxt este habilitados o no en funcion si el usuario va a incluir un nuevo delito
    ItemListener itemListener = new ItemListener() {
        public void itemStateChanged(ItemEvent itemEvent) {
            if (jComboBox3.getSelectedItem().toString().equals("Nuevo Delito")) {
                jTextField14.setEnabled(true);
                jTextField1.setEnabled(true);
                jTextAreaDescNuevoDelito.setEnabled(true);

            } else if (!jComboBox3.getSelectedItem().toString().equals("Nuevo Delito")) {
                jTextField14.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextAreaDescNuevoDelito.setEnabled(false);
            }
        }
    };

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialogInsertarDelito.setLocationRelativeTo(null);
        jDialogInsertarDelito.setVisible(true);    
        actualizarComboDelitos();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //        String titulo = jTextField1.getText();
        //        String duracion = jTextField2.getText();
        //        String letras = jTextArea2.getText();
        //        int id = Integer.parseInt(jTextField4.getText());
        //        String albu = (String)jComboBox1.getSelectedItem();
        //        int album = Integer.parseInt(albu) ;
        //
        //        gesCon.GestorConexion();
        //        // Comprobamos si se va a relizar una insercion de solo cancion o cancion y album y en funcion de esto
        //        //utilizamos un metodo u otro
        //        Object selected = jComboBox1.getSelectedItem();
        //        if(!selected.toString().equals("Nuevo Album")){
        //            gesCon.insertar(titulo,duracion,letras,id,album);
        //        } else {
        //            String _titulo = jTextField7.getText();
        //            int _album = Integer.parseInt(jTextField6.getText());
        //            int _publicacion = Integer.parseInt(jTextField5.getText());
        //            gesCon.insertar_con_commit(titulo, duracion, letras, id, album, _album, _publicacion,_titulo);
        //        }
        //        gesCon.cerrar_conexion();
        //        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonCancelarAddDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAddDelitoActionPerformed
        jDialogInsertarDelito.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarAddDelitoActionPerformed

    private void jButtonAceptarAddDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarAddDelitoActionPerformed
        //Si seleccionamos un delito ya existente se introduce de manera normal
        // si cremaos un nuevo delito se utiliza otro metodo para quitar el autocommit
        //y hacer rollback si no se completa la insercion del nuevo delito y posteriormente el delito asociado a ese preso
        String codDelito = jComboBox3.getSelectedItem().toString().trim();

        if (!codDelito.equals("") && !codDelito.equals("Nuevo Delito")) {

            gesCon.insertarDelitoPreso(preso, codDelito, jTextArea4.getText(), jTextField13.getText());
            gesCon.consulta_Statement("Select * from preso_delito where codigo_preso = '" + preso + "';", jTable2, 0);
            jDialogInsertarDelito.setVisible(false);
            // en la opciones en las que cerramos este jDialog quitamos el listener del combox para que luego
            //Si volvemos a abrir esta pestaña y se cargar nuevos datos en el jcombobox no de errores
//            jComboBox3.removeItemListener(itemListener);

        } else if (codDelito.equals("Nuevo Delito")) {

            codDelito = jTextField1.getText();
            int resultadoInsercion = gesCon.insertarDelitoPresoNuevoDelito(preso, codDelito, jTextArea4.getText(), jTextField13.getText(), jTextAreaDescNuevoDelito.getText(), jTextField14.getText());

            if (resultadoInsercion == 1) {

                jLabelErrorInsetarDelito.setText("Se ha producido un error");
            } else {
                jDialogInsertarDelito.setVisible(false);
//                jComboBox3.removeItemListener(itemListener);
                //cargamos de nuevo los datos en la tabla para que se vea que se ha introducido el delito
                gesCon.consulta_Statement("Select * from preso_delito where codigo_preso = '" + preso + "';", jTable2, 0);
            }

            //Si no se ha seleccionado un codigo de delito y se esta intentando añadir a un preso un delito lo idicamos por un jlabel
        } else {
            jLabelErrorInsetarDelito.setText("Seleccione un codigo de delito");
        }


    }//GEN-LAST:event_jButtonAceptarAddDelitoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //Cuando le damos a buscar en el jDialog de busqueda avanzada, se comprueba que jtext estan rellenos 
        //y en funcion de esto se hace una consulta con estos campos
        String consultaAvanzada = "";
        //variable con la que comprobamos que se trata del primer dato a consultar o no,
        //cada vez que entramos dentro de un if de las consultas se le añade 1 de este modoç
        //excepto la primera vez sera diferente a 0 y se añadira el string adecuado
        int checked = 0;
        //El nombre va primero por lo que no necesita un if en caso de que se haya escogido segundo
        if (!jTextField15.getText().trim().equals("")) {
            consultaAvanzada = "nombre = '" + jTextField15.getText() + "'";
            checked++;
        }
        //El resto de ifs necesitan otro if en su interior para que a la hora de formar el string de la consulta
        //se forme correctamente con el and en caso de no ser el primer valor que se va a buscar
        if (!jTextField16.getText().trim().equals("")) {
            if (checked == 0) {
                consultaAvanzada = "apellidos = '" + jTextField16.getText() + "'";
            } else {
                consultaAvanzada = consultaAvanzada + " and apellidos = '" + jTextField16.getText() + "'";
            }
            checked++;
        }
        if (!jTextField17.getText().trim().equals("")) {
            if (checked == 0) {
                consultaAvanzada = "nacionalidad = '" + jTextField17.getText() + "'";
            } else {
                consultaAvanzada = consultaAvanzada + " and nacionalidad = '" + jTextField17.getText() + "'";
            }
            checked++;
        }
        if (!jTextField19.getText().trim().equals("")) {
            if (checked == 0) {
                consultaAvanzada = "color_piel = '" + jTextField19.getText() + "'";
            } else {
                consultaAvanzada = consultaAvanzada + " and color_piel = '" + jTextField19.getText() + "'";
            }
            checked++;
        }
        if (!jTextField20.getText().trim().equals("")) {
            if (checked == 0) {
                consultaAvanzada = "banda = '" + jTextField20.getText() + "'";
            } else {
                consultaAvanzada = consultaAvanzada + " and banda = '" + jTextField20.getText() + "'";
            }
            checked++;
        }

        System.out.println(consultaAvanzada);
        gesCon.consulta_Statement("Select * from preso where " + consultaAvanzada  , jTable1, 0);
        jDialogBusquedaAvanzada.setVisible(false);
        reseteTextBusquedaAvanzada();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaAvanzadaActionPerformed
        jDialogBusquedaAvanzada.setLocationRelativeTo(null);
        jDialogBusquedaAvanzada.setVisible(true);

    }//GEN-LAST:event_jButtonBusquedaAvanzadaActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jDialogBusquedaAvanzada.setVisible(false);
        reseteTextBusquedaAvanzada();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonBuscarPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPresoActionPerformed
        String consulta = (String) jComboBoxConsultaPresos.getSelectedItem();
        //switch para las cosnultas de los presos, en funcion de el valor seleccionado en el ComboBox 
        //se asocia a una consulta
        switch (consulta.trim()) {
            case "Todos los presos":
                consulta = "Select * from preso";
                break;
            case "Preso con DNI:":
                consulta = "Select * from preso where dni = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Preso con Código:":
                consulta = "Select * from preso where codigo_preso = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Nombre:":
                consulta = "Select * from preso where nombre = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Apellido:":
                consulta = "Select * from preso where apellidos = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Fecha de Nacimiento en:":
                consulta = "Select * from preso where fecha_nacimiento = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Nacionalidad:":
                consulta = "Select * from preso where nacionalidad = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Color de piel:":
                consulta = "Select * from preso where color_piel = '" + jTextFieldConsultaPreso.getText() + "'";
                break;
            case "Presos con Altura:":
                consulta = "Select * from preso where estatura = " + jTextFieldConsultaPreso.getText() + "";
                break;
            case "Presos de la Banda:":
                consulta = "Select * from preso where banda = '" + jTextFieldConsultaPreso.getText() + "'";
                break;

        }
        gesCon.consulta_Statement(consulta, jTable1, 2);
    }//GEN-LAST:event_jButtonBuscarPresoActionPerformed

    private void jButtonAtrasInsertasPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasInsertasPresoActionPerformed
        cambiarPanel(jPanelInicio);
    }//GEN-LAST:event_jButtonAtrasInsertasPresoActionPerformed

    private void jButtonAddPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPresoActionPerformed
        String _telefono = "";
        //chequea si es el primer telefono que se ha introducido para colocar correctamente la consulta 
        boolean primero = true;
        
        String _codigo_preso = jTextField28.getText().trim();
        String _dni = jTextField8.getText().trim();
        String _nombre = jTextField18.getText().trim();
        String _apellidos = jTextField21.getText().trim();
        String _fecha_nacimiento = jTextField22.getText().trim();
        String _lugar_nacimiento = jTextField25.getText().trim();
        String _nacionalidad = jTextField23.getText().trim();
        String _estatura = jTextField26.getText().trim();
        String _color_piel = jTextField24.getText().trim();
        String _banda = jTextField27.getText().trim();
        String _fotoPreso = jTextField29.getText().trim();
        
        if(!jTextField30.getText().trim().equals("")){
            _telefono =  "telefono('Movil','"+jTextField30.getText()+"')";
            primero = false;
        }
        if(!jTextField31.getText().trim().equals("")){
            if(primero){
             _telefono =  "telefono('Abogado','"+jTextField31.getText()+"')";
                primero = false;
            }else { _telefono = _telefono + ",telefono('Abogado','"+jTextField31.getText()+"')";}      
        }
        if(!jTextField32.getText().trim().equals("")){
             if(primero){
               _telefono =  "telefono('Familiar','"+jTextField32.getText()+"')";
            }else { _telefono = _telefono + ",telefono('Familiar','"+jTextField32.getText()+"')";}  
        }
        
        gesCon.insertarPreso(_codigo_preso, _dni, _nombre, _apellidos, _fecha_nacimiento, _lugar_nacimiento, 
                _nacionalidad, _estatura, _color_piel, _banda, _fotoPreso, _telefono);
        cargaPerfilPreso(_codigo_preso);
        cambiarPanel(jPanelPerfilPreso);
        //actualizamos la variable preso para que se pueden realizar los insert a continuacion si se le quieren añadir delitos
        //al preso que se acaba de crear 
        preso = _codigo_preso;
    }//GEN-LAST:event_jButtonAddPresoActionPerformed

    private void jButtonNuevoPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoPresoActionPerformed
        cambiarPanel(jPanelAddPreso);
    }//GEN-LAST:event_jButtonNuevoPresoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String _codigo_preso = jTextFieldCodigoPresoPerfil.getText().trim();
        String _dni = jTextFieldDniPresoPerfil.getText().trim();
        String _nombre = jTextFieldNombrePresoPerfil.getText().trim();
        String _apellidos = jTextFieldApellidoPresoPerfil.getText().trim();
        Format formatter = new SimpleDateFormat("dd-MM-yyyy");
        String nacimiento = formatter.format(jDateChooser1.getDate());
        String _fecha_nacimiento = nacimiento;
  
        String _nacionalidad = jTextFieldNacionalidadPresoPerfil.getText().trim();
        String _estatura = jTextFieldAlturaPresoPerfil.getText().trim();
        String _color_piel = jTextFieldPielPresoPerfil.getText().trim();
        String _banda = jTextFieldPielPresoPerfil.getText().trim();
   
        int modificacion = gesCon.modificarDatosPreso(_codigo_preso,_dni,_nombre,_apellidos,_fecha_nacimiento,_nacionalidad,_estatura,_color_piel,_banda);
        if(modificacion == 0 ){
            jLabelErrorPerfil.setText("Se han modificado los datos correctamente");
        } else {
            jLabelErrorPerfil.setText("Se ha producido un error al modificar los datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialogModificarTelefono.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonModificarTelPresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTelPresoActionPerformed
       jDialogModificarTelefono.setLocationRelativeTo(null);
        jDialogModificarTelefono.setVisible(true);
        cargaTelefonos();
        //reseteamos las variables
        nuevoTelAbogado = true; nuevoTelFamiliar = true; nuevoTelMovil = true;
        
        if(!jTextField2.getText().trim().equals("")){
            nuevoTelMovil = false;
        }
        if(!jTextField3.getText().trim().equals("")){
            nuevoTelAbogado = false;
        }
        if(!jTextField4.getText().trim().equals("")){
            nuevoTelFamiliar = false;
        }
        
        
    }//GEN-LAST:event_jButtonModificarTelPresoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String telMovil = jTextField2.getText();
        String telAbogado = jTextField3.getText();
        String telFamiliar = jTextField4.getText();
        
        //Condiciones para que en el caso de que no hubiera un telefon creado de ese tipo o estuviera en blanco
        //y posteriormente al dar al boton de modificar telefonos sigue en blanco para que no modifique ni cree nada para ese tipo
        boolean actuarMovil = true; boolean actuarAbogado = true; boolean actuarFamiliar = true;
        
         if(telMovil.equals("") & nuevoTelMovil){
            actuarMovil = false;
        }
        if(telAbogado.equals("") & nuevoTelAbogado){
           actuarAbogado = false;
        }
        if(telFamiliar.equals("") & nuevoTelFamiliar){
            actuarFamiliar = false;
        }
   
        gesCon.modificarTelefono(preso,telMovil,telAbogado,telFamiliar,nuevoTelMovil,nuevoTelAbogado,nuevoTelFamiliar,actuarMovil,actuarAbogado,actuarFamiliar);
        
        jDialogModificarTelefono.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void reseteTextBusquedaAvanzada() {
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
    }

    private void cambiarPanel(JPanel panel) {
        jPanelContenedor.removeAll();
        jPanelContenedor.add(panel);
        jPanelContenedor.repaint();
        jPanelContenedor.revalidate();

    }

    public void cargaTelefonos(){
        //Reseteamos los textField en caso de que esten los datos de otro pereso que hayamos consultado antes 
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
        jTextField2.setText(gesCon.cargarTelefonoPreso(preso, "Movil"));
        jTextField3.setText(gesCon.cargarTelefonoPreso(preso, "Abogado"));
        jTextField4.setText(gesCon.cargarTelefonoPreso(preso, "Familiar"));
    }
    
    //Metodo para actualizar todos los datos del perfil de un preso cuando hacemos clikc derecho sobre este en la primera tabla
    public void cargaPerfilPreso(String preso) {
        List datosPreso = new ArrayList();

        try {

            //Para ejecutar la consulta
            Statement s = gesCon.conn1.createStatement();
            //Ejecutamos la consulta que escribimos en la caja de texto
            //y los datos lo almacenamos en un ResultSet
            ResultSet rs = s.executeQuery("Select * from preso where codigo_preso = '" + preso + "'");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();

            //guardamos los datos del preso en array para luego colocarlos en los jtextfields
            while (rs.next()) {
                for (int j = 0; j < cantidadColumnas; j++) {
                    
                    if(j==4){
                    datosPreso.add(rs.getDate(1 + j));
                    }else {
                    datosPreso.add(rs.getString(1 + j));
                    }
                }
            }
            rs.close();
            s.close();

            jTextFieldCodigoPresoPerfil.setText(datosPreso.get(0).toString());
            jTextFieldDniPresoPerfil.setText(datosPreso.get(1).toString());
            jTextFieldNombrePresoPerfil.setText(datosPreso.get(2).toString());
            jTextFieldApellidoPresoPerfil.setText(datosPreso.get(3).toString());
            jDateChooser1.setDate((Date)datosPreso.get(4));
            jTextFieldNacionalidadPresoPerfil.setText(datosPreso.get(6).toString());
            jTextFieldAlturaPresoPerfil.setText(datosPreso.get(7).toString());
            jTextFieldPielPresoPerfil.setText(datosPreso.get(8).toString());
            jTextFieldBandaPreso.setText(datosPreso.get(9).toString());
            
            jComboBox1.removeAllItems();
                
             List listaTelefono = new ArrayList();
            s = gesCon.conn1.createStatement();
            //los telefonos al ser una nested table no sabemos cuantos son, hacemos una consulta del tipo de telefono y el numero
            //que tiene separados por un doble concat, no deja hacer un concat de mas de dos valores, y luego se lo añadimos al combobox
            //del perfil del preso en el que nos encontramos
            rs = s.executeQuery("select CONCAT(concat(t.tipo,'     '), t.Num_telefono) from preso p, table(p.telefono) t where p.codigo_preso = '"+preso+"'");
            rsMd = rs.getMetaData();
            cantidadColumnas = rsMd.getColumnCount();
            while (rs.next()) {
                for (int j = 0; j < cantidadColumnas; j++) {
                    listaTelefono.add(rs.getString(1 + j));
                }
            }
            rs.close();
            s.close();
            
            for(int i=0; i<listaTelefono.size(); i++){
                 jComboBox1.addItem(listaTelefono.get(i).toString());
            }
  
                actualizarFoto(datosPreso.get(11).toString());
            
            

//            gesCon.consulta_Statement("Select * from preso_delito where codigo_preso = '" + preso + "';", jTable2, 0);
            
                gesCon.consulta_Statement("select p.codigo_preso.codigo_preso, p.codigo_delito.codigo_delito,"
               + " P.CIRCUSTANCIAS, P.UBICACION from preso_delito p where p.codigo_preso = (SELECT REF(pres) "
                + "FROM preso pres where pres.codigo_preso ='"+ preso +"')", jTable2, 0);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void actualizarFoto(String foto) {
        //metodo que ejecutamos cuando cargamos un perfil de un preso, primero intentamos cargar su foto con la url 
        //que tenemos en la base de datos, si nos da error Null Pointer Exception (significa que la foto no existe)
        //utilizaremos una generic que guardamos en la cartpeta y que en principio nunca dará error

        //Da igual que tamaño de imagen se proporcione con este metodo se escala al jlabel de destino
        //si la voto es un string vacio pueder ser que en la base de datos no se tenga la foto y al cojer el dato se guarda como tal
        //si ocurre ese usamos la predefinida
        if (foto.trim().equals("")) {
            foto = "/imagenes/anonimo.jpg";
        }

        try {
            ImageIcon img = new javax.swing.ImageIcon(getClass().getResource(foto));
            Image myimage = img.getImage();
            Image newimage = myimage.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon definitivo = new ImageIcon(newimage);
            jLabel3.setIcon(definitivo);

        } catch (NullPointerException e) {

            ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/imagenes/anonimo.jpg"));
            Image myimage = img.getImage();
            Image newimage = myimage.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon definitivo = new ImageIcon(newimage);
            jLabel3.setIcon(definitivo);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAceptarAddDelito;
    private javax.swing.JButton jButtonAddPreso;
    private javax.swing.JButton jButtonAtrasInsertasPreso;
    private javax.swing.JButton jButtonAtrasPerfilPreso;
    private javax.swing.JButton jButtonBuscarPreso;
    private javax.swing.JButton jButtonBusquedaAvanzada;
    private javax.swing.JButton jButtonCancelarAddDelito;
    private javax.swing.JButton jButtonEliminarPreso;
    private javax.swing.JButton jButtonModificarTelPreso;
    private javax.swing.JButton jButtonNuevoPreso;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxConsultaPresos;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialogBusquedaAvanzada;
    private javax.swing.JDialog jDialogInsertarDelito;
    private javax.swing.JDialog jDialogModificarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorInsetarDelito;
    private javax.swing.JLabel jLabelErrorPerfil;
    private javax.swing.JPanel jPanelAddDelito;
    private javax.swing.JPanel jPanelAddPreso;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelPerfilPreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextAreaDescNuevoDelito;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldAlturaPresoPerfil;
    private javax.swing.JTextField jTextFieldApellidoPresoPerfil;
    private javax.swing.JTextField jTextFieldBandaPreso;
    private javax.swing.JTextField jTextFieldCodigoPresoPerfil;
    private javax.swing.JTextField jTextFieldConsultaPreso;
    private javax.swing.JTextField jTextFieldDniPresoPerfil;
    private javax.swing.JTextField jTextFieldNacionalidadPresoPerfil;
    private javax.swing.JTextField jTextFieldNombrePresoPerfil;
    private javax.swing.JTextField jTextFieldPielPresoPerfil;
    // End of variables declaration//GEN-END:variables
}
